/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareComparisonRouteImport } from './routes/compare.$comparison'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseRouteImport } from './routes/courses.$course'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as UniversitiesSlugIndexRouteImport } from './routes/universities.$slug.index'
import { Route as UniversitiesSlugCoursesCourseRouteImport } from './routes/universities.$slug.courses.$course'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompareRoute,
} as any)
const CompareComparisonRoute = CompareComparisonRouteImport.update({
  id: '/$comparison',
  path: '/$comparison',
  getParentRoute: () => CompareRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseRoute = CoursesCourseRouteImport.update({
  id: '/$course',
  path: '/$course',
  getParentRoute: () => CoursesRoute,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UniversitiesRoute,
} as any)
const UniversitiesSlugIndexRoute = UniversitiesSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => UniversitiesRoute,
} as any)
const UniversitiesSlugCoursesCourseRoute =
  UniversitiesSlugCoursesCourseRouteImport.update({
    id: '/$slug/courses/$course',
    path: '/$slug/courses/$course',
    getParentRoute: () => UniversitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/authors': typeof AuthorsRoute
  '/blogs': typeof BlogsRoute
  '/career': typeof CareerRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/reviews': typeof ReviewsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tools': typeof ToolsRoute
  '/universities': typeof UniversitiesRouteWithChildren
  '/compare/$comparison': typeof CompareComparisonRoute
  '/courses/$course': typeof CoursesCourseRoute
  '/compare/': typeof CompareIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/universities/$slug/': typeof UniversitiesSlugIndexRoute
  '/universities/$slug/courses/$course': typeof UniversitiesSlugCoursesCourseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/authors': typeof AuthorsRoute
  '/blogs': typeof BlogsRoute
  '/career': typeof CareerRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/reviews': typeof ReviewsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tools': typeof ToolsRoute
  '/compare/$comparison': typeof CompareComparisonRoute
  '/courses/$course': typeof CoursesCourseRoute
  '/compare': typeof CompareIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/universities': typeof UniversitiesIndexRoute
  '/universities/$slug': typeof UniversitiesSlugIndexRoute
  '/universities/$slug/courses/$course': typeof UniversitiesSlugCoursesCourseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/authors': typeof AuthorsRoute
  '/blogs': typeof BlogsRoute
  '/career': typeof CareerRoute
  '/categories': typeof CategoriesRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rankings': typeof RankingsRoute
  '/reviews': typeof ReviewsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tools': typeof ToolsRoute
  '/universities': typeof UniversitiesRouteWithChildren
  '/compare/$comparison': typeof CompareComparisonRoute
  '/courses/$course': typeof CoursesCourseRoute
  '/compare/': typeof CompareIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/universities/$slug/': typeof UniversitiesSlugIndexRoute
  '/universities/$slug/courses/$course': typeof UniversitiesSlugCoursesCourseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/authors'
    | '/blogs'
    | '/career'
    | '/categories'
    | '/compare'
    | '/contact'
    | '/courses'
    | '/news'
    | '/privacy-policy'
    | '/rankings'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/tags'
    | '/terms-and-conditions'
    | '/tools'
    | '/universities'
    | '/compare/$comparison'
    | '/courses/$course'
    | '/compare/'
    | '/courses/'
    | '/universities/'
    | '/universities/$slug/'
    | '/universities/$slug/courses/$course'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/authors'
    | '/blogs'
    | '/career'
    | '/categories'
    | '/contact'
    | '/news'
    | '/privacy-policy'
    | '/rankings'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/tags'
    | '/terms-and-conditions'
    | '/tools'
    | '/compare/$comparison'
    | '/courses/$course'
    | '/compare'
    | '/courses'
    | '/universities'
    | '/universities/$slug'
    | '/universities/$slug/courses/$course'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/authors'
    | '/blogs'
    | '/career'
    | '/categories'
    | '/compare'
    | '/contact'
    | '/courses'
    | '/news'
    | '/privacy-policy'
    | '/rankings'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/tags'
    | '/terms-and-conditions'
    | '/tools'
    | '/universities'
    | '/compare/$comparison'
    | '/courses/$course'
    | '/compare/'
    | '/courses/'
    | '/universities/'
    | '/universities/$slug/'
    | '/universities/$slug/courses/$course'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AuthorsRoute: typeof AuthorsRoute
  BlogsRoute: typeof BlogsRoute
  CareerRoute: typeof CareerRoute
  CategoriesRoute: typeof CategoriesRoute
  CompareRoute: typeof CompareRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  NewsRoute: typeof NewsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RankingsRoute: typeof RankingsRoute
  ReviewsRoute: typeof ReviewsRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TagsRoute: typeof TagsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ToolsRoute: typeof ToolsRoute
  UniversitiesRoute: typeof UniversitiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/$comparison': {
      id: '/compare/$comparison'
      path: '/$comparison'
      fullPath: '/compare/$comparison'
      preLoaderRoute: typeof CompareComparisonRouteImport
      parentRoute: typeof CompareRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$course': {
      id: '/courses/$course'
      path: '/$course'
      fullPath: '/courses/$course'
      preLoaderRoute: typeof CoursesCourseRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/universities/': {
      id: '/universities/'
      path: '/'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/universities/$slug/': {
      id: '/universities/$slug/'
      path: '/$slug'
      fullPath: '/universities/$slug/'
      preLoaderRoute: typeof UniversitiesSlugIndexRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/universities/$slug/courses/$course': {
      id: '/universities/$slug/courses/$course'
      path: '/$slug/courses/$course'
      fullPath: '/universities/$slug/courses/$course'
      preLoaderRoute: typeof UniversitiesSlugCoursesCourseRouteImport
      parentRoute: typeof UniversitiesRoute
    }
  }
}

interface CompareRouteChildren {
  CompareComparisonRoute: typeof CompareComparisonRoute
  CompareIndexRoute: typeof CompareIndexRoute
}

const CompareRouteChildren: CompareRouteChildren = {
  CompareComparisonRoute: CompareComparisonRoute,
  CompareIndexRoute: CompareIndexRoute,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseRoute: typeof CoursesCourseRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseRoute: CoursesCourseRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface UniversitiesRouteChildren {
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
  UniversitiesSlugIndexRoute: typeof UniversitiesSlugIndexRoute
  UniversitiesSlugCoursesCourseRoute: typeof UniversitiesSlugCoursesCourseRoute
}

const UniversitiesRouteChildren: UniversitiesRouteChildren = {
  UniversitiesIndexRoute: UniversitiesIndexRoute,
  UniversitiesSlugIndexRoute: UniversitiesSlugIndexRoute,
  UniversitiesSlugCoursesCourseRoute: UniversitiesSlugCoursesCourseRoute,
}

const UniversitiesRouteWithChildren = UniversitiesRoute._addFileChildren(
  UniversitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  AuthorsRoute: AuthorsRoute,
  BlogsRoute: BlogsRoute,
  CareerRoute: CareerRoute,
  CategoriesRoute: CategoriesRoute,
  CompareRoute: CompareRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  NewsRoute: NewsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RankingsRoute: RankingsRoute,
  ReviewsRoute: ReviewsRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TagsRoute: TagsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ToolsRoute: ToolsRoute,
  UniversitiesRoute: UniversitiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
